INSERT INTO users (name, age) VALUES ("Elyse", 21);
INSERT INTO users (name, age) VALUES ("Antonio", 15);
INSERT INTO users (name, age) VALUES ("Beetles", 25);
INSERT INTO users (name, age) VALUES ("Ernie", 37);
INSERT INTO users (name, age) VALUES ("Darrien", 30);
INSERT INTO users (name, age) VALUES ("Becky", 18);
INSERT INTO users (name, age) VALUES ("Andre", 3000);
INSERT INTO users (name, age) VALUES ("Kanye", 38);
INSERT INTO users (name, age) VALUES ("Beyonce´", 36);
INSERT INTO users (name, age) VALUES ("Mandy", 40);
INSERT INTO users (name, age) VALUES ("Jennifer", 22);
INSERT INTO users (name, age) VALUES ("Laq'keisha", 28);
INSERT INTO users (name, age) VALUES ("Treyvon", 15);
INSERT INTO users (name, age) VALUES ("Chad", 49);
INSERT INTO users (name, age) VALUES ("Laura Jane", 32);
INSERT INTO users (name, age) VALUES ("Warren G", 21);
INSERT INTO users (name, age) VALUES ("Connie", 24);
INSERT INTO users (name, age) VALUES ("Snoop", 50);
INSERT INTO users (name, age) VALUES ("Erykah", 40);
INSERT INTO users (name, age) VALUES ("Wiz", 39);
