INSERT INTO users (name, age) VALUES ("Elyse", 21);
INSERT INTO users (name, age) VALUES ("Antonio", 15);
INSERT INTO users (name, age) VALUES ("Beetles", 25);
INSERT INTO users (name, age) VALUES ("Ernie", 37);
INSERT INTO users (name, age) VALUES ("Darrien", 30);
INSERT INTO users (name, age) VALUES ("Becky", 18);
INSERT INTO users (name, age) VALUES ("Andre", 3000);
INSERT INTO users (name, age) VALUES ("Kanye", 38);
INSERT INTO users (name, age) VALUES ("Beyonce´", 36);
INSERT INTO users (name, age) VALUES ("Mandy", 40);
INSERT INTO users (name, age) VALUES ("Jennifer", 22);
INSERT INTO users (name, age) VALUES ("Laq'keisha", 28);
INSERT INTO users (name, age) VALUES ("Treyvon", 15);
INSERT INTO users (name, age) VALUES ("Chad", 49);
INSERT INTO users (name, age) VALUES ("Laura Jane Grace", 32);
INSERT INTO users (name, age) VALUES ("Warren G", 21);
INSERT INTO users (name, age) VALUES ("Connie", 24);
INSERT INTO users (name, age) VALUES ("Snoop", 50);
INSERT INTO users (name, age) VALUES ("Erykah", 40);
INSERT INTO users (name, age) VALUES ("Wiz", 39);


INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("fitkids", "health/fitness", 10000, "Sept 1", "June 1");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("art for the people", "art", 15000, "Feb 1", "Aug 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("#codeblack", "technology", 1000000, "Jan 1", "June 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Water Babies", "community", 12500, "Mar 1", "May 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Eat right live long", "health/fitness", 5000, "Feb 1", "July 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Hoverboard sandwich", "technology", 100000, "Dec 1", "Mar 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Elderly Homies", "community", 2000, "Jan 1", "Dec 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Pets!Save!Pets!", "adoption", 50000, "Apr 1", "Aug 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Read a book", "education", 6000, "Aug 1", "May 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Rockstart", "music", 200000, "June 1", "Aug 30");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Animal Bros", "adoption", 7000, "Apr 1", "Oct 30");
